import {VERSION,RESOURCE_NAMES,BUILDINGS,FOCI,EDICTS,SEASON_NAMES,newGame,seasonOf,yearOf,dayOfSeason,capacity,foodCapacity,dailyEstimate,riskLevel,eventInfo,decide,construct,setFocus,setEdict,advance,objective,achievements,validateSave,endingDescription,EVENT_COUNT} from './engine.js';
import {VillageWorld, weatherForDay, BUILDING_SLOTS} from './world.js';

const KEY=`bramwood-save-v${VERSION}`;
const $=id=>document.getElementById(id);
const escapeHtml=(value)=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
let state;
let world;
let activeTab='aldea';
let toastTimer;
const PRIOR_KEY='bramwood-save-v3';
const ico={food:'◈',wood:'♧',stone:'◆',gold:'✦',herbs:'❧'};
const int=n=>new Intl.NumberFormat('es-ES').format(n);
function openSave(){try{const raw=localStorage.getItem(KEY);return raw?validateSave(JSON.parse(raw)):newGame();}catch(e){console.warn('Guardado no disponible:',e);return newGame();}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('save-status').textContent='● Guardado local';}catch(e){$('save-status').textContent='⚠ Sin guardado';}}
function notify(message){const t=$('toast');t.textContent=message;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),3600);}
function apply(action){const before=state?{day:state.day,population:state.population,resources:{...state.resources},stats:{...state.stats},journal:state.journal.map(j=>j.day+':'+j.title)}:null;let result;try{result=action(state);}catch(e){console.error(e);notify('Error inesperado. Prueba a recargar.');return;}if(result.ok){save();render();if(result.progressed)renderDayRecap(before,result);if(result.message)notify(result.message);}else notify(result.message||'Acción no disponible.');}
function setTab(tab){if(!$(tab))return;activeTab=tab;document.querySelectorAll('.tab').forEach(el=>{el.classList.toggle('active',el.dataset.tab===tab);if(el.dataset.tab===tab)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});document.querySelectorAll('.tab-content').forEach(el=>el.classList.toggle('active',el.id===tab));window.scrollTo({top:Math.max(0,document.querySelector('.tabs').getBoundingClientRect().top+window.scrollY-6),behavior:'smooth'});}
function labelCost(cost){const keys=Object.entries(cost||{});return keys.map(([k,v])=>`${ico[k]||''} ${v} ${RESOURCE_NAMES[k]||k}`).join(' · ');}
function renderResources(){const d=dailyEstimate(state);const list=[['food','Comida'],['wood','Madera'],['stone','Piedra'],['gold','Coronas'],['herbs','Hierbas']];let html=list.map(([key,name])=>{const val=state.resources[key];const rate=key in d?d[key]:null;return `<div class="resource"><div class="resource-top"><span>${name}</span><span class="resource-symbol">${ico[key]}</span></div><div class="resource-value">${int(val)}</div><div class="resource-rate ${rate!==null&&rate<0?'negative':''}">${rate===null?'Reservas':(rate>0?'+':'')+rate+' / día'}</div></div>`;}).join('');html+=`<div class="resource"><div class="resource-top"><span>Habitantes</span><span class="resource-symbol">♟</span></div><div class="resource-value">${int(state.population)}</div><div class="resource-rate">${int(capacity(state))} plazas en casas</div></div>`;$('resourceStrip').innerHTML=html;}
function renderEvent(){const area=$('eventContainer');if(!state.alive){area.innerHTML=`<section class="event-card"><div class="event-pill">FIN DE PARTIDA</div><h2>El último capítulo</h2><p>${escapeHtml(state.ending)}</p><div class="choices"><button class="choice" id="endNew"><span class="choice-index">✦</span><span class="choice-body"><strong>Empezar una nueva historia</strong><small>Todas las decisiones vuelven a estar abiertas.</small></span><span class="choice-arrow">→</span></button></div></section>`;$('endNew').addEventListener('click',confirmNewGame);return;}
  const e=eventInfo(state);
  if(!e){area.innerHTML=state.lastOutcome&&state.lastOutcome.day===state.day?`<section class="event-message"><div class="section-label">EL CONSEJO HA HABLADO</div><h3>La decisión está tomada</h3><p>${escapeHtml(state.lastOutcome.text)}</p></section>`:`<section class="event-message"><div class="section-label">UNA TARDE TRANQUILA</div><h3>Por ahora, hay calma.</h3><p>Usa tus órdenes para levantar edificios o cambiar las prioridades. Cuando estés listo, deja avanzar los días. La aldea no esperará eternamente.</p></section>`;return;}
  area.innerHTML=`<section class="event-card"><div class="event-header"><span class="event-pill">✦ ${escapeHtml(e.category)}</span><span class="section-label">DÍA ${state.day}</span></div><h2>${escapeHtml(e.title)}</h2><div class="speaker">↳ ${escapeHtml(e.speaker)} informa al consejo</div><p>${escapeHtml(e.text)}</p><div class="choices">${e.choices.map((c,i)=>`<button class="choice" data-choice="${escapeHtml(c.id)}" ${!c.affordable?'disabled':''}><span class="choice-index">${i+1}</span><span class="choice-body"><strong>${escapeHtml(c.label)}</strong><small>${escapeHtml(c.summary)} ${Object.keys(c.cost).length?' · Coste: '+escapeHtml(labelCost(c.cost)):''}${!c.affordable?' · RECURSOS INSUFICIENTES':''}</small></span><span class="choice-arrow">→</span></button>`).join('')}</div></section>`;
  area.querySelectorAll('[data-choice]').forEach(btn=>btn.addEventListener('click',()=>apply(s=>decide(s,btn.dataset.choice))));
}
function renderVillage(){if(world)world.setState(state);const season=seasonOf(state.day);$('seasonBadge').textContent=`✦ ${season}`;$('timeText').textContent=`Año ${roman(yearOf(state.day))} · Día ${state.day} · ${dayOfSeason(state.day)}/18 de ${season.toLowerCase()}`;$('chapterText').textContent=state.day<19?'Capítulo I · Echar raíces':state.day<55?'Capítulo II · Antes de la nieve':state.day<91?'Capítulo III · Nuevos caminos':'Capítulo IV · Tu legado';$('populationView').textContent=`♟ ${state.population} habitantes`;$('defenseView').textContent=`⚔ Defensa ${state.stats.security}`;$('viewWeather').textContent=`${weatherIcon(weatherForDay(state.day).type)} ${weatherForDay(state.day).type.toUpperCase()} · ${season.toUpperCase()}`;const view=document.querySelector('.village-view');view.classList.toggle('winter',season==='Invierno');view.classList.toggle('autumn',season==='Otoño');view.classList.toggle('has-tower',state.buildings.watch>0);view.classList.toggle('has-wall',state.buildings.palisade>0);
  const evt=!!state.currentEvent;$('nextDay').disabled=evt||!state.alive;$('skipDays').disabled=evt||!state.alive;$('turnHelp').textContent=!state.alive?'La aldea ha dejado de existir.':evt?'Un acontecimiento espera tu decisión.':`${state.actions} órdenes disponibles · ${state.focus?FOCI[state.focus].name:'-'}`;
  const d=dailyEstimate(state);$('dailyEstimate').textContent=`Proyección: ${d.food>=0?'+':''}${d.food} comida · ${d.wood>=0?'+':''}${d.wood} madera · ${d.gold>=0?'+':''}${d.gold} coronas / día`;
  renderEvent();renderResources();
  $('moodBars').innerHTML=[['morale','Ánimo colectivo'],['security','Defensa de la aldea'],['prosperity','Prosperidad']].map(([k,label])=>{const v=state.stats[k];return `<div class="mood-bar ${v<35?'low':''}"><div class="mood-head"><span>${label}</span><b>${v} / 100</b></div><div class="bar-track"><div class="bar-fill" style="width:${v}%"></div></div></div>`;}).join('');
  const obj=objective(state);$('objectiveTitle').textContent=obj.title;$('objectiveText').textContent=obj.detail;$('objectiveBar').style.width=`${obj.progress}%`;$('objectivePercent').textContent=`${obj.progress}%`;
  const messages=[];
  if(state.population>capacity(state))messages.push(['⌂',`Hay ${state.population-capacity(state)} habitantes sin plaza de vivienda. La moral bajará cada día.`]);
  if(state.resources.food<35)messages.push(['◈','Las reservas de comida son peligrosamente bajas. Prepara campos o reduce raciones.']);
  if(season==='Otoño')messages.push(['❄','El invierno comienza en menos de 19 días. La producción agrícola se desplomará.']);
  if(season==='Invierno')messages.push(['❄','El invierno reduce las cosechas y vuelve el bosque más peligroso.']);
  if(state.flags.banditTax)messages.push(['⚔','Los bandidos cobran un tributo de dos coronas por día.']);
  if(state.queued.length)messages.push(['✉',`${state.queued.length} consecuencia(s) pendientes. Los hechos volverán a llamar a tu puerta.`]);
  messages.push(['♧',`Nivel de amenaza: ${riskLevel(state).toLowerCase()}. La defensa determina la gravedad de algunos ataques.`]);
  $('whispers').innerHTML=messages.slice(0,5).map(([i,t])=>`<div class="whisper"><span class="whisper-mark">${i}</span><span>${escapeHtml(t)}</span></div>`).join('');
}
function roman(n){if(n>20)return String(n);return ['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX'][n]||String(n);}
function renderCouncil(){const enabled=!state.currentEvent&&state.alive&&state.actions>0;$('ordersCount').textContent=`${state.actions} orden${state.actions===1?'':'es'}`;
  $('focusGrid').innerHTML=Object.entries(FOCI).map(([id,v])=>`<button class="option-row ${state.focus===id?'selected':''}" data-focus="${id}" ${!enabled||state.focus===id?'disabled':''}><span><strong>${escapeHtml(v.name)}</strong><small>${escapeHtml(v.detail)}</small></span><span class="tick">${state.focus===id?'✓':'→'}</span></button>`).join('');
  $('edictGrid').innerHTML=Object.entries(EDICTS).map(([id,v])=>`<button class="option-row ${state.edict===id?'selected':''}" data-edict="${id}" ${!enabled||state.edict===id?'disabled':''}><span><strong>${escapeHtml(v.name)}</strong><small>${escapeHtml(v.detail)}</small></span><span class="tick">${state.edict===id?'✓':'→'}</span></button>`).join('');
  $('buildGrid').innerHTML=Object.entries(BUILDINGS).map(([id,b])=>{const count=state.buildings[id];const maxed=count>=b.max;const affordable=Object.entries(b.cost).every(([k,v])=>state.resources[k]>=v);return `<div class="build-card"><div class="build-head"><strong>${escapeHtml(b.name)}</strong><span class="count">${count}/${b.max}</span></div><small>${escapeHtml(b.description)}</small><div class="build-cost">${escapeHtml(labelCost(b.cost))}</div><button data-build="${id}" ${!enabled||!affordable||maxed?'disabled':''}>${maxed?'Completado':affordable?'Construir →':'Faltan recursos'}</button></div>`;}).join('');
  document.querySelectorAll('[data-focus]').forEach(el=>el.addEventListener('click',()=>apply(s=>setFocus(s,el.dataset.focus))));
  document.querySelectorAll('[data-edict]').forEach(el=>el.addEventListener('click',()=>apply(s=>setEdict(s,el.dataset.edict))));
  document.querySelectorAll('[data-build]').forEach(el=>el.addEventListener('click',()=>apply(s=>construct(s,el.dataset.build))));
}
function renderPeople(){$('peopleGrid').innerHTML=state.notables.map(p=>`<article class="person-card"><div class="person-head"><div class="person-avatar">${escapeHtml(p.name[0])}</div><div><h3>${escapeHtml(p.name)}</h3><div class="role">${escapeHtml(p.role)}</div></div></div><p>${escapeHtml(p.trait)}</p><div class="person-status"><span>Confianza</span><b>${p.alive?p.trust+'/100':'—'}</b></div><div class="bar-track"><div class="bar-fill" style="width:${p.alive?p.trust:0}%"></div></div><div class="person-status"><span>Salud</span><b>${p.alive?p.health+'/100':'Fallecido'}</b></div><div class="bar-track"><div class="bar-fill" style="width:${p.alive?p.health:0}%"></div></div></article>`).join('');
  const count=state.notables.filter(p=>p.alive).length;const average=Math.round(state.notables.filter(p=>p.alive).reduce((a,p)=>a+p.trust,0)/(count||1));$('peopleSummary').innerHTML=`<div class="section-label">UNA ALDEA DE PERSONAS</div><h3>${state.population} vecinos · ${count} figuras conocidas</h3><p>Confianza media en el consejo: <strong>${average}/100</strong>. El resto de los habitantes vive y trabaja fuera del consejo; el hambre, la vivienda y la seguridad también afectan a sus vidas.</p>`;
}
function renderChronicle(){$('journalList').innerHTML=state.journal.map(entry=>`<div class="journal-entry"><div class="journal-time">AÑO ${roman(yearOf(entry.day))}<div>DÍA ${entry.day}</div></div><div><h4>${escapeHtml(entry.title)}</h4><p>${escapeHtml(entry.text)}</p></div></div>`).join('');$('legacyTitle').textContent=endingDescription(state);$('achievementList').innerHTML=achievements(state).map(a=>`<div class="achievement ${a.done?'done':''}"><span>${a.done?'✦':'◇'}</span><span>${escapeHtml(a.title)}</span></div>`).join('');
  const series=state.history.slice(-45);const max=Math.max(120,...series.map(x=>x.food));const points=series.map((x,i)=>`${10+i*(280/Math.max(1,series.length-1))},${120-(x.food/max)*105}`).join(' ');const morale=series.map((x,i)=>`${10+i*(280/Math.max(1,series.length-1))},${120-(x.morale/100)*105}`).join(' ');$('chartArea').innerHTML=`<svg class="chart-svg" viewBox="0 0 310 140" role="img" aria-label="Evolución de comida y moral"><path d="M10 15V120H300" stroke="#536b52" fill="none" stroke-width="1"/><path d="M10 67H300" stroke="#536b52" fill="none" stroke-dasharray="3 5"/><polyline points="${points}" fill="none" stroke="#e9c680" stroke-width="3" stroke-linejoin="round"/><polyline points="${morale}" fill="none" stroke="#8fcaa1" stroke-width="2.3" stroke-linejoin="round"/></svg><div class="chart-note">— <span style="color:#e9c680">Comida</span> &nbsp; — <span style="color:#8fcaa1">Moral</span> · últimos ${series.length} días</div>`;
}
function weatherIcon(name){return {Despejado:'☀',Nublado:'☁',Lluvia:'☂',Nevada:'❄',Viento:'☷'}[name]||'☀';}
function showMapSelection(item){const target=$('mapSelection'),title=$('mapSelectionTitle'),detail=$('mapSelectionDetail'),symbol=$('mapSelectionIcon'),btn=$('mapSelectionButton');target.classList.toggle('selected',!!item);btn.hidden=true;
 if(!item){title.textContent='Conoce tu aldea';detail.textContent='Selecciona un edificio, camino o habitante. La aldea crece contigo.';symbol.textContent='⌂';return;}
 if(item.type==='building'){const b=BUILDINGS[item.id];symbol.textContent=({farm:'❀',houses:'⌂',lumber:'♧',quarry:'◆',watch:'♜',granary:'◈',market:'✦',infirmary:'✚',palisade:'⚔'})[item.id];title.textContent=`${item.name} · ${item.level}/${state.buildings[item.id]}`;detail.textContent=b.description;btn.hidden=false;btn.textContent='Ver construcciones →';}
 else if(item.type==='person'){symbol.textContent='♟';title.textContent=item.name;const notable=state.notables.find(n=>n.name===item.name);detail.textContent=`${item.role}${notable?` · Confianza ${notable.trust}/100 · Salud ${notable.health}/100`:''}`;}
 else{symbol.textContent='◇';title.textContent=item.name;detail.textContent=item.name==='Río de Bram'?'El agua cruza las tierras al este. Las estaciones transforman su cauce.':item.name.startsWith('Camino')?'Los senderos unen los hogares, talleres y campos del asentamiento.':'Bosques y claros rodean Bramwood. Los árboles pueden protegerse o talarse.';}
}
function renderDayRecap(before,result){if(!before||state.day===before.day)return;const output=$('daySummary');const diff=[...Object.keys(state.resources),'population'].map(k=>{const a=k==='population'?before.population:before.resources[k],b=k==='population'?state.population:state.resources[k];const d=b-a;return d===0?'':`<span class="recap-stat ${d<0?'loss':'gain'}">${escapeHtml(RESOURCE_NAMES[k]||'Habitantes')}: ${d>0?'+':''}${d}</span>`;}).filter(Boolean);
 const fresh=state.journal.filter(j=>!before.journal.includes(j.day+':'+j.title)).slice(0,2);output.hidden=false;output.innerHTML=`<div class="recap-head"><strong>☼ Amanecer del día ${state.day}</strong><button class="recap-close" type="button" title="Ocultar resumen" aria-label="Ocultar resumen">×</button></div><div class="recap-stats">${diff.join('')||'<span>Sin cambios relevantes en las reservas</span>'}</div><p>${result.progressed>1?`Han pasado ${result.progressed} días. `:''}${fresh.length?escapeHtml(fresh.map(j=>j.text).join(' · ')):escapeHtml(`La aldea continúa su vida. ${state.currentEvent?'El consejo debe atender un nuevo acontecimiento.':'Puedes preparar el próximo día.'}`)}</p>`;output.querySelector('.recap-close').addEventListener('click',()=>{output.hidden=true;});}
function render(){renderVillage();renderCouncil();renderPeople();renderChronicle();if(world&&world.selected)showMapSelection(world.selected);}
function download(name,content,mime='application/json'){const blob=new Blob([content],{type:mime});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),1500);}
function confirmNewGame(){if(!confirm('¿Empezar otra historia? La partida actual se sustituirá. Exporta antes la partida si quieres conservarla.'))return;state=newGame();save();render();setTab('aldea');if($('settingsDialog').open)$('settingsDialog').close();notify('Una nueva historia empieza en Bramwood.');}
function setup(){state=openSave();world=new VillageWorld($('worldCanvas'),{onSelect:showMapSelection,onWeather:()=>{}});render();$('zoomIn').addEventListener('click',()=>world.zoom(1.2));$('zoomOut').addEventListener('click',()=>world.zoom(1/1.2));$('zoomHome').addEventListener('click',()=>world.home());$('mapSelectionButton').addEventListener('click',()=>setTab('consejo'));$('tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)setTab(b.dataset.tab);});$('nextDay').addEventListener('click',()=>apply(s=>advance(s,1)));$('skipDays').addEventListener('click',()=>apply(s=>advance(s,7)));$('settingsBtn').addEventListener('click',()=>$('settingsDialog').showModal());$('closeSettings').addEventListener('click',()=>$('settingsDialog').close());$('newGame').addEventListener('click',confirmNewGame);$('exportSave').addEventListener('click',()=>{download(`bramwood-partida-dia-${state.day}.json`,JSON.stringify(state,null,2));notify('Partida exportada.');});$('importSave').addEventListener('click',()=>$('importInput').click());$('importInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>3000000)throw Error('El archivo es demasiado grande.');const imported=validateSave(JSON.parse(await f.text()));if(!confirm(`¿Cargar la partida del día ${imported.day}? Sustituirá la partida actual.`))return;state=imported;save();render();$('settingsDialog').close();setTab('aldea');notify('Partida importada.');}catch(err){notify('No se pudo importar: '+err.message);}finally{e.target.value='';}});
  $('exportChronicle').addEventListener('click',()=>{const text=['BRAMWOOD — CRÓNICA DE UNA ALDEA',`Año ${yearOf(state.day)} · Día ${state.day}`,endingDescription(state),'',...state.journal.slice().reverse().map(j=>`Día ${j.day} · ${j.title}\n${j.text}\n`)].join('\n');download(`bramwood-cronica-dia-${state.day}.txt`,text,'text/plain;charset=utf-8');notify('Crónica exportada.');});
  window.addEventListener('keydown',e=>{if(e.target.matches('input, textarea, select')||$('settingsDialog').open)return;if(state.currentEvent&&['1','2','3'].includes(e.key)){const btn=document.querySelectorAll('[data-choice]')[Number(e.key)-1];if(btn&&!btn.disabled)btn.click();}});
  if('serviceWorker' in navigator && (location.protocol==='https:'||location.hostname==='localhost'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
setup();
